### PR TITLE
Add API:Allpages support

### PR DESCRIPTION
**Pull request by elifoster**
This simply adds support for the Allpages API. @retep998 this is needed for that Recipe/Crafting stuff I'm working on.

### CODE REVIEW

**Comment by elifoster** [comment]
@retep998 Any word on getting this reviewed or closed? It's been almost a year.

**Comment by tomodachi94** [comment]
6 years later...

**Comment by elifoster** [comment]
I don't even remember what I was using this for. I'll just go ahead and close it. I probably ended up using our Ruby gem for it anyway

**Comment by retep998** [comment]
I'm pretty sure this can already be done using just the public facing API.

**Pull request closed without merging**
